/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_drahflow_ar_CameraTracker */

#ifndef _Included_name_drahflow_ar_CameraTracker
#define _Included_name_drahflow_ar_CameraTracker
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_name_drahflow_ar_CameraTracker_SVO_1prepare
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jdouble, jdouble);

JNIEXPORT void JNICALL Java_name_drahflow_ar_CameraTracker_SVO_1processFrame
  (JNIEnv *, jclass, jfloatArray, jlong);

JNIEXPORT void JNICALL Java_name_drahflow_ar_CameraTracker_SVO_1processAccelerometer
  (JNIEnv *, jclass, jfloatArray, jlong);

JNIEXPORT void JNICALL Java_name_drahflow_ar_CameraTracker_SVO_1processGyroscope
  (JNIEnv *, jclass, jfloatArray, jlong);

JNIEXPORT void JNICALL Java_name_drahflow_ar_CameraTracker_SVO_1getTransformation
  (JNIEnv *, jclass, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
