/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_drahflow_ar_CameraTracker */

#ifndef _Included_name_drahflow_ar_CameraTracker
#define _Included_name_drahflow_ar_CameraTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     name_drahflow_ar_CameraTracker
 * Method:    SVO_prepare
 * Signature: (IIFFDD)V
 */
JNIEXPORT void JNICALL Java_name_drahflow_ar_CameraTracker_SVO_1prepare
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jdouble, jdouble);

/*
 * Class:     name_drahflow_ar_CameraTracker
 * Method:    SVO_processFrame
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_name_drahflow_ar_CameraTracker_SVO_1processFrame
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
